name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - uses: cachix/install-nix-action@v13

      - uses: cachix/cachix-action@v10
        with:
          name: dapp

      - name: Install solc 0.8.6
        run: nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_6

      - name: Run tests
        run: nix-shell --pure --run 'make test'
