name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: cachix/install-nix-action@v13
      - uses: cachix/cachix-action@v10
        with:
          name: dapp

      - name: Build and run tests briefly
        if: ${{ github.ref != 'refs/heads/master' && github.base_ref != 'master' }} # Only run brief fuzz if we're not pushing to master or making a PR going to master.
        run: nix-shell --run 'CI=false make'

      - name: Build and run tests deeply
        if: ${{ github.ref == 'refs/heads/master' || github.base_ref == 'master' }} # Only run deep fuzz if we're pushing to master or making a PR going to master.
        run: nix-shell --run 'make'
